spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.136.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8090

wechat:
  mpAppId: wx6b550b2970a8a11f
  mpAppSecret: 1fcdf43ae679cbf7f3d3a5aa306b293a
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://catalinali.ngrok.xiaomiqiu.cn/sell/pay/notify
